# Generated by Django 5.0.6 on 2024-07-22 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('not_completed', 'Not Completed'), ('in_progress', 'In Progress'), ('completed', 'Completed')], default='not_completed', max_length=20),
        ),
    ]
