# Generated by Django 5.0.6 on 2024-07-22 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0002_remove_task_completed_task_status"),
        ("todo", "0002_task_detail"),
    ]

    operations = []
